# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Dependabot for package version updates
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    open-pull-requests-limit: 2
    groups:
      pip-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      pip-major:
        patterns:
          - "*"
        update-types:
          - major
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    open-pull-requests-limit: 1
    groups:
      github-actions-all:
        patterns:
          - "*"
    labels:
      - dependencies
